# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'paintScreen.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1133, 742)
        font = QtGui.QFont()
        font.setPointSize(42)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        Form.setFont(font)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Image/windowsIcon/images.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("../Image/windowsIcon/images.jpg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        Form.setWindowIcon(icon)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: rgb(160,82,45)")
        self.screen = QtWidgets.QLabel(Form)
        self.screen.setGeometry(QtCore.QRect(0, 0, 731, 741))
        self.screen.setText("")
        self.screen.setScaledContents(True)
        self.screen.setObjectName("screen")
        self.blue_channel = QtWidgets.QSlider(Form)
        self.blue_channel.setGeometry(QtCore.QRect(780, 160, 201, 21))
        self.blue_channel.setMaximum(255)
        self.blue_channel.setOrientation(QtCore.Qt.Horizontal)
        self.blue_channel.setObjectName("blue_channel")
        self.green_channel = QtWidgets.QSlider(Form)
        self.green_channel.setGeometry(QtCore.QRect(780, 130, 201, 22))
        self.green_channel.setMaximum(255)
        self.green_channel.setOrientation(QtCore.Qt.Horizontal)
        self.green_channel.setObjectName("green_channel")
        self.red_channel = QtWidgets.QSlider(Form)
        self.red_channel.setGeometry(QtCore.QRect(780, 100, 201, 22))
        self.red_channel.setMaximum(255)
        self.red_channel.setOrientation(QtCore.Qt.Horizontal)
        self.red_channel.setObjectName("red_channel")
        self.color = QtWidgets.QLabel(Form)
        self.color.setGeometry(QtCore.QRect(1030, 110, 81, 61))
        self.color.setStyleSheet("background-color: rgb(0,0,0)")
        self.color.setText("")
        self.color.setObjectName("color")
        self.brush_color_title = QtWidgets.QLabel(Form)
        self.brush_color_title.setGeometry(QtCore.QRect(750, 30, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.brush_color_title.setFont(font)
        self.brush_color_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.brush_color_title.setObjectName("brush_color_title")
        self.favorite_colors_title = QtWidgets.QLabel(Form)
        self.favorite_colors_title.setGeometry(QtCore.QRect(750, 200, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.favorite_colors_title.setFont(font)
        self.favorite_colors_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.favorite_colors_title.setObjectName("favorite_colors_title")
        self.favorite_color1 = QtWidgets.QPushButton(Form)
        self.favorite_color1.setGeometry(QtCore.QRect(760, 272, 75, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.favorite_color1.setFont(font)
        self.favorite_color1.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.favorite_color1.setStyleSheet("")
        self.favorite_color1.setText("")
        self.favorite_color1.setObjectName("favorite_color1")
        self.favorite_color2 = QtWidgets.QPushButton(Form)
        self.favorite_color2.setGeometry(QtCore.QRect(850, 272, 75, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.favorite_color2.setFont(font)
        self.favorite_color2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.favorite_color2.setStyleSheet("")
        self.favorite_color2.setText("")
        self.favorite_color2.setObjectName("favorite_color2")
        self.favorite_color3 = QtWidgets.QPushButton(Form)
        self.favorite_color3.setGeometry(QtCore.QRect(940, 272, 75, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.favorite_color3.setFont(font)
        self.favorite_color3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.favorite_color3.setStyleSheet("")
        self.favorite_color3.setText("")
        self.favorite_color3.setObjectName("favorite_color3")
        self.favorite_color4 = QtWidgets.QPushButton(Form)
        self.favorite_color4.setGeometry(QtCore.QRect(1030, 272, 75, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.favorite_color4.setFont(font)
        self.favorite_color4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.favorite_color4.setStyleSheet("")
        self.favorite_color4.setText("")
        self.favorite_color4.setObjectName("favorite_color4")
        self.favorite_color5 = QtWidgets.QPushButton(Form)
        self.favorite_color5.setGeometry(QtCore.QRect(760, 320, 75, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.favorite_color5.setFont(font)
        self.favorite_color5.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.favorite_color5.setStyleSheet("")
        self.favorite_color5.setText("")
        self.favorite_color5.setObjectName("favorite_color5")
        self.favorite_color6 = QtWidgets.QPushButton(Form)
        self.favorite_color6.setGeometry(QtCore.QRect(850, 320, 75, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.favorite_color6.setFont(font)
        self.favorite_color6.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.favorite_color6.setStyleSheet("")
        self.favorite_color6.setText("")
        self.favorite_color6.setObjectName("favorite_color6")
        self.favorite_color7 = QtWidgets.QPushButton(Form)
        self.favorite_color7.setGeometry(QtCore.QRect(940, 320, 75, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.favorite_color7.setFont(font)
        self.favorite_color7.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.favorite_color7.setStyleSheet("")
        self.favorite_color7.setText("")
        self.favorite_color7.setObjectName("favorite_color7")
        self.favorite_color8 = QtWidgets.QPushButton(Form)
        self.favorite_color8.setGeometry(QtCore.QRect(1030, 320, 75, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.favorite_color8.setFont(font)
        self.favorite_color8.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.favorite_color8.setAutoFillBackground(False)
        self.favorite_color8.setStyleSheet("")
        self.favorite_color8.setText("")
        self.favorite_color8.setObjectName("favorite_color8")
        self.brush_paint_size_title = QtWidgets.QLabel(Form)
        self.brush_paint_size_title.setGeometry(QtCore.QRect(750, 390, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.brush_paint_size_title.setFont(font)
        self.brush_paint_size_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.brush_paint_size_title.setObjectName("brush_paint_size_title")
        self.brush_paint_size = QtWidgets.QSlider(Form)
        self.brush_paint_size.setGeometry(QtCore.QRect(760, 470, 221, 22))
        self.brush_paint_size.setMinimum(3)
        self.brush_paint_size.setMaximum(150)
        self.brush_paint_size.setProperty("value", 8)
        self.brush_paint_size.setOrientation(QtCore.Qt.Horizontal)
        self.brush_paint_size.setObjectName("brush_paint_size")
        self.size_value = QtWidgets.QLabel(Form)
        self.size_value.setGeometry(QtCore.QRect(990, 460, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.size_value.setFont(font)
        self.size_value.setAlignment(QtCore.Qt.AlignCenter)
        self.size_value.setObjectName("size_value")
        self.color_value_title = QtWidgets.QLabel(Form)
        self.color_value_title.setGeometry(QtCore.QRect(1020, 80, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.color_value_title.setFont(font)
        self.color_value_title.setAlignment(QtCore.Qt.AlignCenter)
        self.color_value_title.setObjectName("color_value_title")
        self.paint_brush_size_title = QtWidgets.QLabel(Form)
        self.paint_brush_size_title.setGeometry(QtCore.QRect(990, 430, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.paint_brush_size_title.setFont(font)
        self.paint_brush_size_title.setAlignment(QtCore.Qt.AlignCenter)
        self.paint_brush_size_title.setObjectName("paint_brush_size_title")
        self.operation_title = QtWidgets.QLabel(Form)
        self.operation_title.setGeometry(QtCore.QRect(750, 520, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.operation_title.setFont(font)
        self.operation_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.operation_title.setObjectName("operation_title")
        self.rotation_slider = QtWidgets.QSlider(Form)
        self.rotation_slider.setGeometry(QtCore.QRect(770, 610, 221, 22))
        self.rotation_slider.setMaximum(360)
        self.rotation_slider.setOrientation(QtCore.Qt.Horizontal)
        self.rotation_slider.setObjectName("rotation_slider")
        self.rotation_value = QtWidgets.QLabel(Form)
        self.rotation_value.setGeometry(QtCore.QRect(1000, 600, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.rotation_value.setFont(font)
        self.rotation_value.setAlignment(QtCore.Qt.AlignCenter)
        self.rotation_value.setObjectName("rotation_value")
        self.rotaion_degress_title = QtWidgets.QLabel(Form)
        self.rotaion_degress_title.setGeometry(QtCore.QRect(1000, 570, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rotaion_degress_title.setFont(font)
        self.rotaion_degress_title.setAlignment(QtCore.Qt.AlignCenter)
        self.rotaion_degress_title.setObjectName("rotaion_degress_title")
        self.rotation_title = QtWidgets.QLabel(Form)
        self.rotation_title.setGeometry(QtCore.QRect(750, 570, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.rotation_title.setFont(font)
        self.rotation_title.setAlignment(QtCore.Qt.AlignCenter)
        self.rotation_title.setObjectName("rotation_title")
        self.erase_title = QtWidgets.QLabel(Form)
        self.erase_title.setGeometry(QtCore.QRect(750, 650, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.erase_title.setFont(font)
        self.erase_title.setAlignment(QtCore.Qt.AlignCenter)
        self.erase_title.setObjectName("erase_title")
        self.erase_button = QtWidgets.QPushButton(Form)
        self.erase_button.setGeometry(QtCore.QRect(770, 690, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.erase_button.setFont(font)
        self.erase_button.setStyleSheet("background-color: white")
        self.erase_button.setObjectName("erase_button")
        self.save_draw_button = QtWidgets.QPushButton(Form)
        self.save_draw_button.setGeometry(QtCore.QRect(1004, 10, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.save_draw_button.setFont(font)
        self.save_draw_button.setAutoFillBackground(False)
        self.save_draw_button.setStyleSheet("background-color: white")
        self.save_draw_button.setObjectName("save_draw_button")
        self.blue_channel_value = QtWidgets.QLabel(Form)
        self.blue_channel_value.setGeometry(QtCore.QRect(990, 160, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.blue_channel_value.setFont(font)
        self.blue_channel_value.setAlignment(QtCore.Qt.AlignCenter)
        self.blue_channel_value.setObjectName("blue_channel_value")
        self.green_channel_value = QtWidgets.QLabel(Form)
        self.green_channel_value.setGeometry(QtCore.QRect(990, 130, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.green_channel_value.setFont(font)
        self.green_channel_value.setAlignment(QtCore.Qt.AlignCenter)
        self.green_channel_value.setObjectName("green_channel_value")
        self.red_channel_value = QtWidgets.QLabel(Form)
        self.red_channel_value.setGeometry(QtCore.QRect(990, 100, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.red_channel_value.setFont(font)
        self.red_channel_value.setAlignment(QtCore.Qt.AlignCenter)
        self.red_channel_value.setObjectName("red_channel_value")
        self.red_letter = QtWidgets.QLabel(Form)
        self.red_letter.setGeometry(QtCore.QRect(750, 100, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.red_letter.setFont(font)
        self.red_letter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.red_letter.setObjectName("red_letter")
        self.green_letter = QtWidgets.QLabel(Form)
        self.green_letter.setGeometry(QtCore.QRect(750, 130, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.green_letter.setFont(font)
        self.green_letter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.green_letter.setObjectName("green_letter")
        self.blue_letter = QtWidgets.QLabel(Form)
        self.blue_letter.setGeometry(QtCore.QRect(750, 160, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.blue_letter.setFont(font)
        self.blue_letter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.blue_letter.setObjectName("blue_letter")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Paint Screen"))
        self.brush_color_title.setText(_translate("Form", "Paint Brush Color"))
        self.favorite_colors_title.setText(_translate("Form", "Favorite Colors"))
        self.brush_paint_size_title.setText(_translate("Form", "Brush Paint Size"))
        self.size_value.setText(_translate("Form", "8"))
        self.color_value_title.setText(_translate("Form", "Current Color"))
        self.paint_brush_size_title.setText(_translate("Form", "Size"))
        self.operation_title.setText(_translate("Form", "Operations"))
        self.rotation_value.setText(_translate("Form", "0"))
        self.rotaion_degress_title.setText(_translate("Form", "Degrees"))
        self.rotation_title.setText(_translate("Form", "Rotation"))
        self.erase_title.setText(_translate("Form", "Erase"))
        self.erase_button.setText(_translate("Form", "Erase"))
        self.save_draw_button.setText(_translate("Form", "Save"))
        self.blue_channel_value.setText(_translate("Form", "0"))
        self.green_channel_value.setText(_translate("Form", "0"))
        self.red_channel_value.setText(_translate("Form", "0"))
        self.red_letter.setText(_translate("Form", "R"))
        self.green_letter.setText(_translate("Form", "G"))
        self.blue_letter.setText(_translate("Form", "B"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
